name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ELECTRON_DISABLE_SANDBOX : 1

    steps:
    - uses: actions/checkout@v1
    - name: Install, lint and build
      run: |
        npm ci
        npm run lint
        npm run build:ci
    - name: Run tests
      uses: mujo-code/puppeteer-headful@master
      with:
        args: npm run test
